<?php

namespace Database\Seeders;

use App\Models\VehicleModel;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class VehicleModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $models = array(
            array(
                'brand' => 'Toyota',
                'model' => 'Avanza',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 106,
                'torque' => 126,
                'top_speed' => 180,
                'acceleration' => 11.5,
                'daily_rate' => 400000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Rush',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 103,
                'torque' => 136,
                'top_speed' => 170,
                'acceleration' => 14.4,
                'daily_rate' => 500000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Agya',
                'vehicle_type' => 'Family',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 87,
                'torque' => 113,
                'top_speed' => 160,
                'acceleration' => 19.7,
                'daily_rate' => 250000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Calya',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 87,
                'torque' => 108,
                'top_speed' => 170,
                'acceleration' => 12.4,
                'daily_rate' => 350000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Innova',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 137,
                'torque' => 183,
                'top_speed' => 200,
                'acceleration' => 15.2,
                'daily_rate' => 600000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Hiace Commuter',
                'vehicle_type' => 'Minibus',
                'capacity' => 16,
                'trunk' => 10,
                'HP' => 134,
                'torque' => 300,
                'top_speed' => 145,
                'acceleration' => 24.1,
                'daily_rate' => 1250000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Alphard',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 5,
                'HP' => 178,
                'torque' => 234,
                'top_speed' => 200,
                'acceleration' => 8.9,
                'daily_rate' => 1000000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Fortuner',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 148,
                'torque' => 400,
                'top_speed' => 190,
                'acceleration' => 10.2,
                'daily_rate' => 600000,
            ),
            array(
                'brand' => 'Toyota',
                'model' => 'Camry Hybrid',
                'vehicle_type' => 'Luxury',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 201,
                'torque' => 243,
                'top_speed' => 210,
                'acceleration' => 7.5,
                'daily_rate' => 1000000,
            ),
            array(
                'brand' => 'Daihatsu',
                'model' => 'Ayla',
                'vehicle_type' => 'Family',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 87,
                'torque' => 113,
                'top_speed' => 180,
                'acceleration' => 14.7,
                'daily_rate' => 250000,
            ),
            array(
                'brand' => 'Daihatsu',
                'model' => 'Xenia',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 105,
                'torque' => 138,
                'top_speed' => 170,
                'acceleration' => 14.4,
                'daily_rate' => 400000,
            ),
            array(
                'brand' => 'Daihatsu',
                'model' => 'Sigra',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 87,
                'torque' => 108,
                'top_speed' => 170,
                'acceleration' => 12.4,
                'daily_rate' => 325000,
            ),
            array(
                'brand' => 'Daihatsu',
                'model' => 'Terios',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 103,
                'torque' => 136,
                'top_speed' => 170,
                'acceleration' => 14.4,
                'daily_rate' => 500000,
            ),
            array(
                'brand' => 'Honda',
                'model' => 'Brio',
                'vehicle_type' => 'Family',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 89,
                'torque' => 110,
                'top_speed' => 150,
                'acceleration' => 12.9,
                'daily_rate' => 250000,
            ),
            array(
                'brand' => 'Honda',
                'model' => 'Mobilio',
                'vehicle_type' => 'Family',
                'capacity' => 5,
                'trunk' => 3,
                'HP' => 116,
                'torque' => 145,
                'top_speed' => 150,
                'acceleration' => 12.5,
                'daily_rate' => 325000,
            ),
            array(
                'brand' => 'Honda',
                'model' => 'HRV',
                'vehicle_type' => 'Family',
                'capacity' => 5,
                'trunk' => 3,
                'HP' => 119,
                'torque' => 145,
                'top_speed' => 210,
                'acceleration' => 8.7,
                'daily_rate' => 475000,
            ),
            array(
                'brand' => 'Honda',
                'model' => 'CRV',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 187,
                'torque' => 240,
                'top_speed' => 215,
                'acceleration' => 8.9,
                'daily_rate' => 600000,
            ),
            array(
                'brand' => 'Honda',
                'model' => 'Accord',
                'vehicle_type' => 'Luxury',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 187,
                'torque' => 260,
                'top_speed' => 210,
                'acceleration' => 8.1,
                'daily_rate' => 1500000,
            ),
            array(
                'brand' => 'Honda',
                'model' => 'Civic Type R',
                'vehicle_type' => 'Luxury',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 306,
                'torque' => 400,
                'top_speed' => 275,
                'acceleration' => 5.5,
                'daily_rate' => 1500000,
            ),
            array(
                'brand' => 'Suzuki',
                'model' => 'Ertiga',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 2,
                'HP' => 103,
                'torque' => 138,
                'top_speed' => 170,
                'acceleration' => 11.8,
                'daily_rate' => 325000,
            ),
            array(
                'brand' => 'Mitsubishi',
                'model' => 'Xpander',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 104,
                'torque' => 141,
                'top_speed' => 165,
                'acceleration' => 13.5,
                'daily_rate' => 400000,
            ),
            array(
                'brand' => 'Mitsubishi',
                'model' => 'Pajero',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 134,
                'torque' => 324,
                'top_speed' => 190,
                'acceleration' => 11.8,
                'daily_rate' => 600000,
            ),
            array(
                'brand' => 'Hyundai',
                'model' => 'Palisade',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 197,
                'torque' => 440,
                'top_speed' => 210,
                'acceleration' => 7.2,
                'daily_rate' => 600000,
            ),
            array(
                'brand' => 'Mercedes',
                'model' => 'SLS AMG',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 1,
                'HP' => 420,
                'torque' => 650,
                'top_speed' => 317,
                'acceleration' => 3.8,
                'daily_rate' => 8000000,
            ),
            array(
                'brand' => 'Mercedes',
                'model' => 'S Class',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 2,
                'HP' => 326,
                'torque' => 700,
                'top_speed' => 250,
                'acceleration' => 5.4,
                'daily_rate' => 7000000,
            ),
            array(
                'brand' => 'Mercedes',
                'model' => 'E Class',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 2,
                'HP' => 282,
                'torque' => 600,
                'top_speed' => 250,
                'acceleration' => 6.1,
                'daily_rate' => 7000000,
            ),
            array(
                'brand' => 'Mercedes',
                'model' => 'S Class Maybach',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 2,
                'HP' => 603,
                'torque' => 900,
                'top_speed' => 250,
                'acceleration' => 4.5,
                'daily_rate' => 15000000,
            ),
            array(
                'brand' => 'Porsche',
                'model' => '911 Carrera',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 1,
                'HP' => 380,
                'torque' => 450,
                'top_speed' => 293,
                'acceleration' => 4.2,
                'daily_rate' => 8000000,
            ),
            array(
                'brand' => 'Ford',
                'model' => 'Mustang',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 2,
                'HP' => 395,
                'torque' => 515,
                'top_speed' => 237,
                'acceleration' => 5.2,
                'daily_rate' => 8000000,
            ),
            array(
                'brand' => 'Nissan',
                'model' => 'Xtrail',
                'vehicle_type' => 'Family',
                'capacity' => 7,
                'trunk' => 3,
                'HP' => 169,
                'torque' => 233,
                'top_speed' => 200,
                'acceleration' => 12.4,
                'daily_rate' => 600000,
            ),
            array(
                'brand' => 'Nissan',
                'model' => 'R35 GTR',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 2,
                'HP' => 562,
                'torque' => 637,
                'top_speed' => 320,
                'acceleration' => 2.7,
                'daily_rate' => 8000000,
            ),
            array(
                'brand' => 'Mini',
                'model' => 'Cabriolet',
                'vehicle_type' => 'Luxury',
                'capacity' => 4,
                'trunk' => 2,
                'HP' => 189,
                'torque' => 280,
                'top_speed' => 228,
                'acceleration' => 7.1,
                'daily_rate' => 3000000,
            ),
            array(
                'brand' => 'BMW',
                'model' => 'M4 Competition',
                'vehicle_type' => 'Luxury',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 530,
                'torque' => 650,
                'top_speed' => 290,
                'acceleration' => 3.6,
                'daily_rate' => 7000000,
            ),
            array(
                'brand' => 'BMW',
                'model' => 'Series 5',
                'vehicle_type' => 'Luxury',
                'capacity' => 5,
                'trunk' => 2,
                'HP' => 261,
                'torque' => 620,
                'top_speed' => 235,
                'acceleration' => 5.7,
                'daily_rate' => 5000000,
            ),
        );

        foreach ($models as $model) {
            $model['vehicle_image'] = '/vehicle-image/' . $model['model'] . '.png';
            VehicleModel::create($model);
        }
    }
}
